#!/bin/bash

# Mettre un lien de la classe Dynacase.filter.php de filtre dans /usr/share/php/PHP/Beautifier/Filter/

set -e

dir=`dirname -- "$0"`
TMP_OUT=`mktemp -- "$1.XXXXXX.bo"`
echo $dir
#filter="Pear(add_header=$dir/header.txt) ArrayNested()"
#filter="Default(), ArrayNested()"
filter="Dynacase(add_header=$dir/header.txt,newline_class=true,newline_function=true), ArrayNested()"
php_beautifier -l "$filter" -- "$1" > "$TMP_OUT"
if [ -s "$TMP_OUT" ]; then
   cp -- "$TMP_OUT" "$1"
   rm -- "$TMP_OUT"
fi

exit 0